wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: huggingface
    huggingface_version: 4.3.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
    start_time: 1629852970
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      4: 3.9.1
      5: 0.12.0
      6: 4.3.3
      8:
      - 5
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 7.5e-05
warmup_steps:
  desc: null
  value: 500
